title: Juanda
email: hello@juanda.me
description: >
  My opinions are mine only.
baseurl: ""
url: "http://juanda.me"
permalink: /:title
twitter_username: juanzuluaga
github_username:  juandazapata

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
excerpt_separator: <!--more-->
google_analytics: UA-37285911-1
disqus:
  shortname: juandazuluaga
